### ISSUE TITLE
Mongo::OperationFailure - Database command 'update' failed: BSON field 'update.multi' is an unknown field.

### ISSUE THREAD

**Issue by venkateshwarant** [maccman/abba#27]
Is ABBA still working? I got this basic issue when I try to set up.

> `
2020-07-21 08:01:58 - Mongo::OperationFailure - Database command 'update' failed: BSON field 'update.multi' is an unknown field.:
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/db.rb:610:in `rescue in command'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/db.rb:606:in `command'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:314:in `block in send_write_command'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:55:in `block in instrument'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:20:in `instrument'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:54:in `instrument'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:313:in `send_write_command'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/collection.rb:1104:in `send_write'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo-1.12.5/lib/mongo/collection.rb:497:in `update'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/modifiers.rb:85:in `modifier_update'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/modifiers.rb:9:in `increment'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/modifiers.rb:117:in `increment'
	/home/vagrant/abba/app/models/variant.rb:22:in `start!'
	/home/vagrant/abba/app.rb:54:in `block in <top (required)>'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/controllers/controller.rb:87:in `start'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
	/home/vagrant/.rvm/gems/ruby-2.1.5/bin/thin:23:in `load'
	/home/vagrant/.rvm/gems/ruby-2.1.5/bin/thin:23:in `<main>'
	/home/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	/home/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
`

**Comment by thg303** [comment]
using mongo 3.2 solved this for me.
